version: 2.1
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers-legacy
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.3-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: cook-with_test
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/cook-with
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.1.4
              bundle install --jobs=4 --retry=3 --path vendor/bundle
              yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop --fail-level W --display-only-fail-level-offenses

  rspec:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers-legacy
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.3-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: cook-with_test
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/cook-with
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.1.4
              bundle install --jobs=4 --retry=3 --path vendor/bundle
              yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
            name: DBの起動を待つ
            command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

  deploy:
    executor: default
    steps:
      - checkout
      - setup
      - add_ssh_keys:
          fingerprints:
            - 90:d5:e1:b8:01:11:39:36:6d:ce:35:8f:51:e5:60:60
      - deploy:
          name: Deploy with Capistrano
          command: bundle exec cap production deploy

workflows:
  version: 2.1
  rubocop_rspec_deploy:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
      - deploy:
          requires:
            - rubocop
            - rspec
          filters:
            branches:
              only: master
