version: 2.1
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run:
          name: データベースのセットアップ
          command: docker-compose exec app bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
           name: Rspecテスト実行
           command: |
             mkdir /tmp/test-results
             TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
             docker-compose exec app bin/rspec --format progress \
                                                                   --format RspecJunitFormatter \
                                                                   --out /tmp/test-results/rspec.xml \
                                                                   $TEST_FILES
      - run:
          name: Rubocopテスト実行
          command: docker-compose exec app rubocop --fail-level W --display-only-fail-level-offenses
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down
